### ISSUE TITLE
Can't run Jupiter example 

### ISSUE THREAD

**Issue by ahmadbelb** [NREL/Panel-Segmentation#18]
I keep getting this error when I run 

```
#CREATE AN INSTANCE OF THE PANELDETECTION CLASS TO RUN THE ANALYSIS
panelseg = pseg.PanelDetection(model_file_path ='./panel_segmentation/VGG16Net_ConvTranpose_complete.h5', 
                               classifier_file_path ='./panel_segmentation/VGG16_classification_model.h5',
                              mounting_classifier_file_path='./panel_segmentation/object_detection_model.pth')

#GENERATE A SATELLITE IMAGE USING THE ASSOCIATED LAT-LONG COORDS AND THE GOOGLE
#MAPS API KEY
img = panelseg.generateSatelliteImage(latitude, longitude,
                                      file_name_save,
                                      google_maps_api_key)
#Show the generated satellite image
plt.imshow(img)
```

SavedModel file does not exist at: ./panel_segmentation/VGG16_classification_model.h5/{saved_model.pbtxt|saved_model.pb}

**Comment by kperrynrel** [comment]
Hey @ahmadbelb when you create the  pseg.PanelDetection() class, use the location of the models in the Panel-segmentation package as the file paths. Were you able to resolve this? I can add a comment addressing this specifically in the Jupyter notebook

**Comment by ahmadbelb** [comment]
I got it working thank you.


Btw, what tool are you using for labelling and creating Masking and
XML files?

**Comment by ahmadbelb** [comment]
Thank you so much !

I think it would be really helpful to add a note about the jupyter error or to try and fix the path issue so it's easier to use the notebook :D

**Comment by kperrynrel** [comment]
@ahmadbelb wanted to give you a heads up--I just pushed up a new PR into master that resolves this path issue, so you no longer need to reference the file paths directly. Thank you for the feedback!
